<?php

namespace MainBundle\Repository;

/**
 * CategoryPrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryPrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
