<?php

namespace MainBundle\Repository;

/**
 * categoryPrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoryPrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
