<?php

namespace MainBundle\Repository;

/**
 * StatutSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
