<?php

namespace MainBundle\Repository;

/**
 * StautSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StautSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
